spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: angelo.develhope@gmail.com
    password: ljlaybondxauhavs
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: truecomm
